/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-09-02 13:12:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.controller.UserCtl;
import in.co.rays.proj4.bean.SubjectBean;
import java.util.List;
import java.util.HashMap;
import in.co.rays.proj4.util.HTMLUtility;
import in.co.rays.proj4.controller.SubjectCtl;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.bean.UserBean;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.controller.LoginCtl;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;

public final class SubjectView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1756818751522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(15);
    _jspx_imports_classes.add("in.co.rays.proj4.controller.UserCtl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.SubjectCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.SubjectBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Add Subject</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form action=\"SubjectCtl\" method=\"POST\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserBean user = (UserBean) session.getAttribute("user");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		if (user != null) {
	
      out.write("\r\n");
      out.write("	<h3>\r\n");
      out.write("		Hi,\r\n");
      out.write("		");
      out.print(user.getFirstName());
      out.write("\r\n");
      out.write("		(");
      out.print(session.getAttribute("role"));
      out.write(")\r\n");
      out.write("	</h3>\r\n");
      out.write("	<a href=\"MyProfileCtl\"><b>My Profile</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<a href=\"UserCtl\"><b>Add User</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"RoleCtl\"><b>Add Role</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"CollegeCtl\"><b>Add College</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"StudentCtl\"><b>Add Student</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<a href=\"CourseCtl\"><b>Add Course</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"SubjectCtl\"><b>Add Subject</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"TimetableCtl\"><b>Add Timetable</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"FacultyCtl\"><b>Add Faculty</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<a href=\"LoginCtl?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><b>Logout</b></a>\r\n");
      out.write("	");

		} else {
	
      out.write("\r\n");
      out.write("	<h3>Hi, Guest</h3>\r\n");
      out.write("	<a href=\"WelcomeCtl\"><b>Welcome</b></a> |\r\n");
      out.write("	<a href=\"LoginCtl\"><b>Login</b></a>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      in.co.rays.proj4.bean.SubjectBean bean = null;
      bean = (in.co.rays.proj4.bean.SubjectBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.proj4.bean.SubjectBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            List<SubjectBean> courseList = (List<SubjectBean>) request.getAttribute("courseList");
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("            <h1 align=\"center\" style=\"margin-bottom: -15; color: navy\">\r\n");
      out.write("                ");

                    if (bean != null && bean.getId() > 0) {
                
      out.write("\r\n");
      out.write("                    Update\r\n");
      out.write("                ");

                    } else {
                
      out.write("\r\n");
      out.write("                    Add\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                Subject\r\n");
      out.write("            </h1>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"height: 15px; margin-bottom: 12px\">\r\n");
      out.write("                <h3 align=\"center\">\r\n");
      out.write("                    <font color=\"green\">\r\n");
      out.write("                        ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("                    </font>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <h3 align=\"center\">\r\n");
      out.write("                    <font color=\"red\">\r\n");
      out.write("                        ");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("                    </font>\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(bean.getCreatedBy());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"modifiedBy\" value=\"");
      out.print(bean.getModifiedBy());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"createdDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDatetime()));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th align=\"left\">Subject<span style=\"color: red\">*</span></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"name\" placeholder=\"Enter Subject Name\" value=\"");
      out.print(DataUtility.getStringData(bean.getName()));
      out.write("\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td style=\"position: fixed;\">\r\n");
      out.write("                        <font color=\"red\">\r\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("name", request));
      out.write("\r\n");
      out.write("                        </font>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th align=\"left\">Course<span style=\"color: red\">*</span></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        ");
      out.print(HTMLUtility.getList("courseId", String.valueOf(bean.getCourseId()), courseList));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td style=\"position: fixed;\">\r\n");
      out.write("                        <font color=\"red\">\r\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("courseId", request));
      out.write("\r\n");
      out.write("                        </font>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th align=\"left\">Description<span style=\"color: red\">*</span></th>\r\n");
      out.write("                    <td align=\"center\">\r\n");
      out.write("                        <textarea style=\"width: 170px; resize: none;\" name=\"description\" rows=\"3\"\r\n");
      out.write("                            placeholder=\"Enter Short description\">");
      out.print(DataUtility.getStringData(bean.getDescription()).trim());
      out.write("</textarea>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td style=\"position: fixed;\">\r\n");
      out.write("                        <font color=\"red\">\r\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("description", request));
      out.write("\r\n");
      out.write("                        </font>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th></th>\r\n");
      out.write("                    ");

                        if (bean != null && bean.getId() > 0) {
                    
      out.write("\r\n");
      out.write("                        <td align=\"left\" colspan=\"2\">\r\n");
      out.write("                            <input type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectCtl.OP_UPDATE);
      out.write("\">\r\n");
      out.write("                            <input type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectCtl.OP_CANCEL);
      out.write("\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    ");

                        } else {
                    
      out.write("\r\n");
      out.write("                        <td align=\"left\" colspan=\"2\">\r\n");
      out.write("                            <input type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectCtl.OP_SAVE);
      out.write("\">\r\n");
      out.write("                            <input type=\"submit\" name=\"operation\" value=\"");
      out.print(SubjectCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
