/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-09-03 11:46:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj4.controller.ORSView;
import java.util.LinkedHashMap;
import in.co.rays.proj4.util.HTMLUtility;
import java.text.SimpleDateFormat;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.controller.TimetableListCtl;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.bean.TimetableBean;
import java.util.List;
import java.util.Iterator;
import in.co.rays.proj4.bean.UserBean;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.controller.LoginCtl;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;

public final class TimetableListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1756899878611L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(16);
    _jspx_imports_classes.add("java.util.LinkedHashMap");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.TimetableListCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.TimetableBean");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.util.HTMLUtility");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Timetable List</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserBean user = (UserBean) session.getAttribute("user");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		if (user != null) {
	
      out.write("\r\n");
      out.write("	<h3>\r\n");
      out.write("		Hi,\r\n");
      out.write("		");
      out.print(user.getFirstName());
      out.write("\r\n");
      out.write("		(");
      out.print(session.getAttribute("role"));
      out.write(")\r\n");
      out.write("	</h3>\r\n");
      out.write("	<a href=\"MyProfileCtl\"><b>My Profile</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<a href=\"UserCtl\"><b>Add User</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"UserListCtl\"><b>User List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"RoleCtl\"><b>Add Role</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"RoleListCtl\"><b>Role List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"CollegeCtl\"><b>Add College</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"CollegeListCtl\"><b>College List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"StudentCtl\"><b>Add Student</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"StudentListCtl\"><b>Student List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<a href=\"CourseCtl\"><b>Add Course</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"CourseListCtl\"><b>Course List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"SubjectCtl\"><b>Add Subject</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"SubjectListCtl\"><b>Subject List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"TimetableCtl\"><b>Add Timetable</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"TimetableListCtl\"><b>Timetable List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"FacultyCtl\"><b>Add Faculty</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"FacultyListCtl\"><b>Faculty List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<a href=\"LoginCtl?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><b>Logout</b></a>\r\n");
      out.write("	");

		} else {
	
      out.write("\r\n");
      out.write("	<h3>Hi, Guest</h3>\r\n");
      out.write("	<a href=\"WelcomeCtl\"><b>Welcome</b></a> |\r\n");
      out.write("	<a href=\"LoginCtl\"><b>Login</b></a>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<h1 align=\"center\" style=\"margin-bottom: -15; color: navy;\">Timetable\r\n");
      out.write("			List</h1>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"height: 15px; margin-bottom: 12px\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\r\n");
      out.write("			</h3>\r\n");
      out.write("			<h3>\r\n");
      out.write("				<font color=\"green\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      in.co.rays.proj4.bean.TimetableBean bean = null;
      bean = (in.co.rays.proj4.bean.TimetableBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.proj4.bean.TimetableBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form action=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("			");

				int pageNo = ServletUtility.getPageNo(request);
				int pageSize = ServletUtility.getPageSize(request);
				int index = ((pageNo - 1) * pageSize) + 1;
				int nextPageSize = DataUtility.getInt(request.getAttribute("nextListSize").toString());

				List<TimetableBean> courseList = (List<TimetableBean>) request.getAttribute("courseList");
				List<TimetableBean> subjectList = (List<TimetableBean>) request.getAttribute("subjectList");

				List<TimetableBean> list = (List<TimetableBean>) ServletUtility.getList(request);
				Iterator<TimetableBean> it = list.iterator();

				if (list.size() != 0) {
			
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\"><input\r\n");
      out.write("				type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<table style=\"width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\"><label><b>Course Name :</b></label> ");
      out.print(HTMLUtility.getList("courseId", String.valueOf(bean.getCourseId()), courseList));
      out.write("&emsp;\r\n");
      out.write("						<label><b>Subject Name :</b></label> ");
      out.print(HTMLUtility.getList("subjectId", String.valueOf(bean.getSubjectId()), subjectList));
      out.write("&emsp;\r\n");
      out.write("						<label><b>Exam Date :</b></label></td>\r\n");
      out.write("					<td align=\"left\"><input type=\"text\" id=\"udate\" name=\"examDate\" placeholder=\"Select Date of Birth\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getDateString(bean.getExamDate()));
      out.write("\">\r\n");
      out.write("				</label>&emsp; <input type=\"submit\" name=\"operation\"\r\n");
      out.write("					value=\"");
      out.print(TimetableListCtl.OP_SEARCH);
      out.write("\">&nbsp; <input\r\n");
      out.write("						type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(TimetableListCtl.OP_RESET);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<table border=\"1\" style=\"width: 100%; border: groove;\">\r\n");
      out.write("				<tr style=\"background-color: #e1e6f1e3;\">\r\n");
      out.write("					<th style=\"width: 5%;\"><input type=\"checkbox\" id=\"selectall\" /></th>\r\n");
      out.write("					<th style=\"width: 5%;\">S.No</th>\r\n");
      out.write("					<th style=\"width: 13%;\">Course Name</th>\r\n");
      out.write("					<th style=\"width: 30%;\">Subject Name</th>\r\n");
      out.write("					<th style=\"width: 7%;\">Semester</th>\r\n");
      out.write("					<th style=\"width: 10%;\">Exam Date</th>\r\n");
      out.write("					<th style=\"width: 15%;\">Exam Time</th>\r\n");
      out.write("					<th style=\"width: 10%;\">Description</th>\r\n");
      out.write("					<th style=\"width: 5%;\">Edit</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				");

					while (it.hasNext()) {
							bean = it.next();
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: center;\"><input type=\"checkbox\"\r\n");
      out.write("						class=\"case\" name=\"ids\" value=\"");
      out.print(bean.getId());
      out.write("\"></td>\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getCourseName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getSubjectName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(bean.getSemester());
      out.write("</td>\r\n");
      out.write("					");

						SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
								String date = sdf.format(bean.getExamDate());
					
      out.write("\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(date);
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getExamTime());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getDescription());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center;\"><a\r\n");
      out.write("						href=\"TimetableCtl?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<table style=\"width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"width: 25%\"><input type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(TimetableListCtl.OP_PREVIOUS);
      out.write("\"\r\n");
      out.write("						");
      out.print(pageNo == 1 ? "" : "disabled" );
      out.write("></td>\r\n");
      out.write("					<td align=\"center\" style=\"width: 25%\"><input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_NEW);
      out.write("\"></td>\r\n");
      out.write("					<td align=\"center\" style=\"width: 25%\"><input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_DELETE);
      out.write("\"></td>\r\n");
      out.write("					<td style=\"width: 25%\" align=\"right\"><input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_NEXT);
      out.write("\"\r\n");
      out.write("						");
      out.print((nextPageSize != 0) ? "" : "disabled");
      out.write("></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			");

				}
				if (list.size() == 0) {
			
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\"><input type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(TimetableListCtl.OP_BACK);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
